# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainIU.ui'
#
# Created: Fri Jun 20 01:32:45 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import GlobalVar

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(815, 746)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(GlobalVar.ICON_LOCATION + "/1403226223_191275.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8(""))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet(_fromUtf8("MainWindow {\n"
" border: 1px solid white;\n"
" border-radius: 3px;\n"
" background: qradialgradient(\n"
"   cx: 0.5, cy: -1.8,\n"
"   fx: 0.5, fy: 0,\n"
"   radius: 2, \n"
"   stop: 0 #9aa9be,\n"
"   stop: 1 #293859);\n"
"  font: bold;\n"
"}\n"
" \n"
"#GlossyFrame QLabel#Title {\n"
" background: transparent;\n"
" color: white;\n"
"}\n"
" \n"
"#GlossyFrame QPushButton {\n"
" color: #white; \n"
" border: 1px solid black;\n"
" border-radius: 3px;\n"
" padding: 1px;\n"
" background: qlineargradient(\n"
"   x1:0, y1:0, x2:0, y2:1,\n"
"   stop:0 #bec1d2,\n"
"   stop: 0.4 #717990, \n"
"   stop: 0.5 #5c637d\n"
"   stop:1 #68778e\n"
" );\n"
" min-height: 36px;\n"
"}\n"
" \n"
"#GlossyFrame QPushButton:pressed {\n"
"background: qlineargradient(\n"
"  x1:0, y1:0, x2:0, y2:1,\n"
"  stop:0 #68778e,\n"
"  stop: 0.4 #5c637d\n"
"  stop: 0.5 #717990,\n"
"  stop:1 #bec1d2\n"
" );\n"
" color: black;\n"
"}\n"
" \n"
"#GlossyFrame QLineEdit {\n"
" background: qlineargradient(\n"
"  x1:0, y1:0, x2:0, y2:1,\n"
"  stop:0 gray,\n"
"  stop: 0.2 white\n"
"  stop:1 white\n"
" );\n"
" border-radius: 1px;\n"
" border: 1px solid black;\n"
" min-height: 24px;\n"
" color: black;\n"
"}\n"
" \n"
"#GlossyFrame QCheckBox {\n"
"     color:  white;\n"
" }\n"
" \n"
"#GlossyFrame QCheckBox::indicator {  \n"
"     position: absolute;\n"
"     height: 27px;\n"
"     width: 64px;\n"
" }\n"
" "))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 341, 61))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.cBoxPhotographer = QtGui.QComboBox(self.groupBox)
        self.cBoxPhotographer.setGeometry(QtCore.QRect(40, 30, 261, 20))
        self.cBoxPhotographer.setObjectName(_fromUtf8("cBoxPhotographer"))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.cBoxPhotographer.setItemText(0, _fromUtf8(""))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.cBoxPhotographer.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 10, 341, 341))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 261, 261))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lEditEventPicker = QtGui.QLineEdit(self.layoutWidget)
        self.lEditEventPicker.setObjectName(_fromUtf8("lEditEventPicker"))
        self.verticalLayout_6.addWidget(self.lEditEventPicker)
        self.lWidgetEvent = QtGui.QListWidget(self.layoutWidget)
        self.lWidgetEvent.setObjectName(_fromUtf8("lWidgetEvent"))
        self.verticalLayout_6.addWidget(self.lWidgetEvent)
        self.btnRefreshEvents = QtGui.QPushButton(self.groupBox_2)
        self.btnRefreshEvents.setGeometry(QtCore.QRect(200, 300, 107, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(GlobalVar.ICON_LOCATION + "/1403176245_48111.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnRefreshEvents.setIcon(icon1)
        self.btnRefreshEvents.setAutoRepeat(False)
        self.btnRefreshEvents.setAutoDefault(False)
        self.btnRefreshEvents.setFlat(False)
        self.btnRefreshEvents.setObjectName(_fromUtf8("btnRefreshEvents"))
        self.groupBox_4 = QtGui.QGroupBox(self.frame)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 70, 341, 281))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(40, 32, 261, 201))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lblNumberSelected = QtGui.QLabel(self.layoutWidget1)
        self.lblNumberSelected.setSizeIncrement(QtCore.QSize(22, 0))
        self.lblNumberSelected.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblNumberSelected.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblNumberSelected.setObjectName(_fromUtf8("lblNumberSelected"))
        self.verticalLayout_7.addWidget(self.lblNumberSelected)
        self.lWidgetPhotoPath = QtGui.QListWidget(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lWidgetPhotoPath.sizePolicy().hasHeightForWidth())
        self.lWidgetPhotoPath.setSizePolicy(sizePolicy)
        self.lWidgetPhotoPath.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lWidgetPhotoPath.setObjectName(_fromUtf8("lWidgetPhotoPath"))
        self.verticalLayout_7.addWidget(self.lWidgetPhotoPath)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(100, 240, 204, 32))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnClear = QtGui.QPushButton(self.layoutWidget2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(GlobalVar.ICON_LOCATION + "/1403176087_23227.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnClear.setIcon(icon2)
        self.btnClear.setObjectName(_fromUtf8("btnClear"))
        self.horizontalLayout_2.addWidget(self.btnClear)
        self.btnBrowse = QtGui.QPushButton(self.layoutWidget2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(GlobalVar.ICON_LOCATION + "/1403176032_70755.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnBrowse.setIcon(icon3)
        self.btnBrowse.setAutoRepeat(False)
        self.btnBrowse.setAutoDefault(False)
        self.btnBrowse.setFlat(False)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.horizontalLayout_2.addWidget(self.btnBrowse)
        self.groupBox_9 = QtGui.QGroupBox(self.frame)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 360, 721, 181))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 20, 191, 141))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 27, 141, 101))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cBoxSenior = QtGui.QCheckBox(self.layoutWidget3)
        self.cBoxSenior.setObjectName(_fromUtf8("cBoxSenior"))
        self.verticalLayout_2.addWidget(self.cBoxSenior)
        self.cBoxJunior = QtGui.QCheckBox(self.layoutWidget3)
        self.cBoxJunior.setObjectName(_fromUtf8("cBoxJunior"))
        self.verticalLayout_2.addWidget(self.cBoxJunior)
        self.cBoxSophomore = QtGui.QCheckBox(self.layoutWidget3)
        self.cBoxSophomore.setObjectName(_fromUtf8("cBoxSophomore"))
        self.verticalLayout_2.addWidget(self.cBoxSophomore)
        self.cBoxFreshmen = QtGui.QCheckBox(self.layoutWidget3)
        self.cBoxFreshmen.setObjectName(_fromUtf8("cBoxFreshmen"))
        self.verticalLayout_2.addWidget(self.cBoxFreshmen)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_7.setGeometry(QtCore.QRect(230, 20, 201, 141))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_7)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 40, 181, 71))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblMontaVista = QtGui.QLabel(self.layoutWidget4)
        self.lblMontaVista.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblMontaVista.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMontaVista.setObjectName(_fromUtf8("lblMontaVista"))
        self.verticalLayout_3.addWidget(self.lblMontaVista)
        self.lblvs = QtGui.QLabel(self.layoutWidget4)
        self.lblvs.setAlignment(QtCore.Qt.AlignCenter)
        self.lblvs.setObjectName(_fromUtf8("lblvs"))
        self.verticalLayout_3.addWidget(self.lblvs)
        self.lEditOpponent = QtGui.QLineEdit(self.layoutWidget4)
        self.lEditOpponent.setObjectName(_fromUtf8("lEditOpponent"))
        self.verticalLayout_3.addWidget(self.lEditOpponent)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_8.setGeometry(QtCore.QRect(450, 20, 251, 141))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_8)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 30, 221, 101))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget5)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cBoxStudentLife = QtGui.QCheckBox(self.layoutWidget5)
        self.cBoxStudentLife.setObjectName(_fromUtf8("cBoxStudentLife"))
        self.gridLayout.addWidget(self.cBoxStudentLife, 0, 0, 1, 1)
        self.cBoxPeople = QtGui.QCheckBox(self.layoutWidget5)
        self.cBoxPeople.setObjectName(_fromUtf8("cBoxPeople"))
        self.gridLayout.addWidget(self.cBoxPeople, 0, 1, 1, 1)
        self.cBoxAcademics = QtGui.QCheckBox(self.layoutWidget5)
        self.cBoxAcademics.setObjectName(_fromUtf8("cBoxAcademics"))
        self.gridLayout.addWidget(self.cBoxAcademics, 1, 0, 1, 1)
        self.cBoxClubs = QtGui.QCheckBox(self.layoutWidget5)
        self.cBoxClubs.setObjectName(_fromUtf8("cBoxClubs"))
        self.gridLayout.addWidget(self.cBoxClubs, 1, 1, 1, 1)
        self.cBoxSports = QtGui.QCheckBox(self.layoutWidget5)
        self.cBoxSports.setObjectName(_fromUtf8("cBoxSports"))
        self.gridLayout.addWidget(self.cBoxSports, 2, 0, 1, 1)
        self.cBoxCrowds = QtGui.QCheckBox(self.layoutWidget5)
        self.cBoxCrowds.setObjectName(_fromUtf8("cBoxCrowds"))
        self.gridLayout.addWidget(self.cBoxCrowds, 2, 1, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.frame)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 560, 721, 71))
        self.groupBox_10.setTitle(_fromUtf8(""))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.layoutWidget6 = QtGui.QWidget(self.groupBox_10)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 30, 701, 32))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.pBarUploadProgress = QtGui.QProgressBar(self.layoutWidget6)
        self.pBarUploadProgress.setProperty("value", 0)
        self.pBarUploadProgress.setObjectName(_fromUtf8("pBarUploadProgress"))
        self.horizontalLayout_4.addWidget(self.pBarUploadProgress)
        self.btnUpload = QtGui.QPushButton(self.layoutWidget6)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(GlobalVar.ICON_LOCATION + "/1403228586_17871.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnUpload.setIcon(icon4)
        self.btnUpload.setCheckable(False)
        self.btnUpload.setAutoExclusive(False)
        self.btnUpload.setObjectName(_fromUtf8("btnUpload"))
        self.horizontalLayout_4.addWidget(self.btnUpload)
        self.lblStatusDisplay = QtGui.QLabel(self.groupBox_10)
        self.lblStatusDisplay.setGeometry(QtCore.QRect(11, 11, 43, 16))
        self.lblStatusDisplay.setObjectName(_fromUtf8("lblStatusDisplay"))
        self.lblCurrentStatus = QtGui.QLabel(self.groupBox_10)
        self.lblCurrentStatus.setGeometry(QtCore.QRect(65, 11, 91, 16))
        self.lblCurrentStatus.setObjectName(_fromUtf8("lblCurrentStatus"))
        self.horizontalLayout.addWidget(self.frame)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(GlobalVar.ICON_LOCATION + "/Upload.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gBoxAdditionalTags = QtGui.QGroupBox(self.tab_2)
        self.gBoxAdditionalTags.setGeometry(QtCore.QRect(450, 200, 301, 171))
        self.gBoxAdditionalTags.setFlat(False)
        self.gBoxAdditionalTags.setObjectName(_fromUtf8("gBoxAdditionalTags"))
        self.layoutWidget7 = QtGui.QWidget(self.gBoxAdditionalTags)
        self.layoutWidget7.setGeometry(QtCore.QRect(20, 30, 261, 131))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget7)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cBoxSearchStudentLife = QtGui.QCheckBox(self.layoutWidget7)
        self.cBoxSearchStudentLife.setObjectName(_fromUtf8("cBoxSearchStudentLife"))
        self.gridLayout_3.addWidget(self.cBoxSearchStudentLife, 0, 0, 1, 1)
        self.cBoxSearchPeople = QtGui.QCheckBox(self.layoutWidget7)
        self.cBoxSearchPeople.setObjectName(_fromUtf8("cBoxSearchPeople"))
        self.gridLayout_3.addWidget(self.cBoxSearchPeople, 0, 1, 1, 1)
        self.cBoxSearchAcademics = QtGui.QCheckBox(self.layoutWidget7)
        self.cBoxSearchAcademics.setObjectName(_fromUtf8("cBoxSearchAcademics"))
        self.gridLayout_3.addWidget(self.cBoxSearchAcademics, 1, 0, 1, 1)
        self.cBoxSearchClubs = QtGui.QCheckBox(self.layoutWidget7)
        self.cBoxSearchClubs.setObjectName(_fromUtf8("cBoxSearchClubs"))
        self.gridLayout_3.addWidget(self.cBoxSearchClubs, 1, 1, 1, 1)
        self.cBoxSearchSports = QtGui.QCheckBox(self.layoutWidget7)
        self.cBoxSearchSports.setObjectName(_fromUtf8("cBoxSearchSports"))
        self.gridLayout_3.addWidget(self.cBoxSearchSports, 2, 0, 1, 1)
        self.cBoxSearchCrowds = QtGui.QCheckBox(self.layoutWidget7)
        self.cBoxSearchCrowds.setObjectName(_fromUtf8("cBoxSearchCrowds"))
        self.gridLayout_3.addWidget(self.cBoxSearchCrowds, 2, 1, 1, 1)
        self.gBoxClassTags = QtGui.QGroupBox(self.tab_2)
        self.gBoxClassTags.setGeometry(QtCore.QRect(450, 20, 301, 101))
        self.gBoxClassTags.setObjectName(_fromUtf8("gBoxClassTags"))
        self.layoutWidget8 = QtGui.QWidget(self.gBoxClassTags)
        self.layoutWidget8.setGeometry(QtCore.QRect(20, 20, 261, 71))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget8)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cBoxSearchSenior = QtGui.QCheckBox(self.layoutWidget8)
        self.cBoxSearchSenior.setObjectName(_fromUtf8("cBoxSearchSenior"))
        self.gridLayout_2.addWidget(self.cBoxSearchSenior, 0, 0, 1, 1)
        self.cBoxSearchJunior = QtGui.QCheckBox(self.layoutWidget8)
        self.cBoxSearchJunior.setObjectName(_fromUtf8("cBoxSearchJunior"))
        self.gridLayout_2.addWidget(self.cBoxSearchJunior, 0, 1, 1, 1)
        self.cBoxSearchSophomore = QtGui.QCheckBox(self.layoutWidget8)
        self.cBoxSearchSophomore.setObjectName(_fromUtf8("cBoxSearchSophomore"))
        self.gridLayout_2.addWidget(self.cBoxSearchSophomore, 1, 0, 1, 1)
        self.cBoxSearchFreshmen = QtGui.QCheckBox(self.layoutWidget8)
        self.cBoxSearchFreshmen.setObjectName(_fromUtf8("cBoxSearchFreshmen"))
        self.gridLayout_2.addWidget(self.cBoxSearchFreshmen, 1, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(450, 380, 301, 131))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.layoutWidget9 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget9.setGeometry(QtCore.QRect(20, 30, 134, 52))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget9)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.dEditStart = QtGui.QDateEdit(self.layoutWidget9)
        self.dEditStart.setDateTime(QtCore.QDateTime(QtCore.QDate(2014, 6, 1), QtCore.QTime(0, 0, 0)))
        self.dEditStart.setDate(QtCore.QDate(2014, 6, 1))
        self.dEditStart.setCalendarPopup(True)
        self.dEditStart.setObjectName(_fromUtf8("dEditStart"))
        self.verticalLayout_4.addWidget(self.dEditStart)
        self.layoutWidget10 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget10.setGeometry(QtCore.QRect(150, 30, 134, 52))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.layoutWidget10)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.dEditEnd = QtGui.QDateEdit(self.layoutWidget10)
        self.dEditEnd.setDate(QtCore.QDate(2015, 4, 1))
        self.dEditEnd.setCalendarPopup(True)
        self.dEditEnd.setObjectName(_fromUtf8("dEditEnd"))
        self.verticalLayout_5.addWidget(self.dEditEnd)
        self.btnResetDateFilter = QtGui.QPushButton(self.groupBox_3)
        self.btnResetDateFilter.setGeometry(QtCore.QRect(190, 90, 101, 31))
        self.btnResetDateFilter.setObjectName(_fromUtf8("btnResetDateFilter"))
        self.gBoxOpponentTags = QtGui.QGroupBox(self.tab_2)
        self.gBoxOpponentTags.setGeometry(QtCore.QRect(450, 130, 301, 61))
        self.gBoxOpponentTags.setObjectName(_fromUtf8("gBoxOpponentTags"))
        self.lEditSearchOpponent = QtGui.QLineEdit(self.gBoxOpponentTags)
        self.lEditSearchOpponent.setGeometry(QtCore.QRect(20, 30, 261, 20))
        self.lEditSearchOpponent.setObjectName(_fromUtf8("lEditSearchOpponent"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(450, 520, 301, 121))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.layoutWidget11 = QtGui.QWidget(self.groupBox_5)
        self.layoutWidget11.setGeometry(QtCore.QRect(20, 40, 261, 61))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget11)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.layoutWidget11)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.lcdNumberTotalImages = QtGui.QLCDNumber(self.layoutWidget11)
        self.lcdNumberTotalImages.setObjectName(_fromUtf8("lcdNumberTotalImages"))
        self.horizontalLayout_7.addWidget(self.lcdNumberTotalImages)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 20, 421, 621))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.layoutWidget12 = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget12.setGeometry(QtCore.QRect(20, 40, 381, 531))
        self.layoutWidget12.setObjectName(_fromUtf8("layoutWidget12"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lEditTagSearch = QtGui.QLineEdit(self.layoutWidget12)
        self.lEditTagSearch.setObjectName(_fromUtf8("lEditTagSearch"))
        self.verticalLayout.addWidget(self.lEditTagSearch)
        self.lWidgetTagSearchResults = QtGui.QListWidget(self.layoutWidget12)
        self.lWidgetTagSearchResults.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.lWidgetTagSearchResults.setObjectName(_fromUtf8("lWidgetTagSearchResults"))
        self.verticalLayout.addWidget(self.lWidgetTagSearchResults)
        self.layoutWidget13 = QtGui.QWidget(self.groupBox_11)
        self.layoutWidget13.setGeometry(QtCore.QRect(14, 580, 391, 32))
        self.layoutWidget13.setObjectName(_fromUtf8("layoutWidget13"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnClearTagSearch = QtGui.QPushButton(self.layoutWidget13)
        self.btnClearTagSearch.setIcon(icon2)
        self.btnClearTagSearch.setObjectName(_fromUtf8("btnClearTagSearch"))
        self.horizontalLayout_6.addWidget(self.btnClearTagSearch)
        self.btnTagSearchRefresh = QtGui.QPushButton(self.layoutWidget13)
        self.btnTagSearchRefresh.setIcon(icon1)
        self.btnTagSearchRefresh.setObjectName(_fromUtf8("btnTagSearchRefresh"))
        self.horizontalLayout_6.addWidget(self.btnTagSearchRefresh)
        self.btnShowInFolder = QtGui.QPushButton(self.layoutWidget13)
        self.btnShowInFolder.setIcon(icon3)
        self.btnShowInFolder.setIconSize(QtCore.QSize(17, 17))
        self.btnShowInFolder.setObjectName(_fromUtf8("btnShowInFolder"))
        self.horizontalLayout_6.addWidget(self.btnShowInFolder)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(GlobalVar.ICON_LOCATION + "/1403175809_3617.ico")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_2, icon6, _fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 815, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuOptions = QtGui.QMenu(self.menuBar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuAbout = QtGui.QMenu(self.menuBar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout_Application = QtGui.QAction(MainWindow)
        self.actionAbout_Application.setObjectName(_fromUtf8("actionAbout_Application"))
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionAbout_Application)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnClear, QtCore.SIGNAL(_fromUtf8("clicked()")), self.lWidgetPhotoPath.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Management", None))
        self.groupBox.setTitle(_translate("MainWindow", "Step 1 - Choose Your Name", None))
        self.cBoxPhotographer.setItemText(1, _translate("MainWindow", "Bill Zhou", None))
        self.cBoxPhotographer.setItemText(2, _translate("MainWindow", "Eric Xu", None))
        self.cBoxPhotographer.setItemText(3, _translate("MainWindow", "Anna Tedijanto", None))
        self.cBoxPhotographer.setItemText(4, _translate("MainWindow", "Sumana Praharaju", None))
        self.cBoxPhotographer.setItemText(5, _translate("MainWindow", "Amy Liu", None))
        self.cBoxPhotographer.setItemText(6, _translate("MainWindow", "Kavya Aswadhati", None))
        self.cBoxPhotographer.setItemText(7, _translate("MainWindow", "Marcus Laguisma", None))
        self.cBoxPhotographer.setItemText(8, _translate("MainWindow", "Leta Dickinson", None))
        self.cBoxPhotographer.setItemText(9, _translate("MainWindow", "Alli Case", None))
        self.cBoxPhotographer.setItemText(10, _translate("MainWindow", "Yiting Li", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Step 3 - Choose a Event", None))
        self.lEditEventPicker.setPlaceholderText(_translate("MainWindow", "Type to Search...", None))
        self.btnRefreshEvents.setText(_translate("MainWindow", "Refresh", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Step 2 - Choose Your Photos", None))
        self.lblNumberSelected.setText(_translate("MainWindow", "0  Selected", None))
        self.btnClear.setText(_translate("MainWindow", "Clear", None))
        self.btnBrowse.setText(_translate("MainWindow", "Browse", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Step 4 - Choose Tags (Recommended)", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Class Tags", None))
        self.cBoxSenior.setText(_translate("MainWindow", "Seniors", None))
        self.cBoxJunior.setText(_translate("MainWindow", "Juniors", None))
        self.cBoxSophomore.setText(_translate("MainWindow", "Sophomores", None))
        self.cBoxFreshmen.setText(_translate("MainWindow", "Freshmens", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Opponent Tag", None))
        self.lblMontaVista.setText(_translate("MainWindow", "Monta Vista", None))
        self.lblvs.setText(_translate("MainWindow", "vs.", None))
        self.lEditOpponent.setPlaceholderText(_translate("MainWindow", "Opponent (if applicable)", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Additional Tags", None))
        self.cBoxStudentLife.setText(_translate("MainWindow", "Student Life", None))
        self.cBoxPeople.setText(_translate("MainWindow", "People", None))
        self.cBoxAcademics.setText(_translate("MainWindow", "Academics", None))
        self.cBoxClubs.setText(_translate("MainWindow", "Clubs", None))
        self.cBoxSports.setText(_translate("MainWindow", "Sports", None))
        self.cBoxCrowds.setText(_translate("MainWindow", "Crowds", None))
        self.btnUpload.setText(_translate("MainWindow", "Upload", None))
        self.lblStatusDisplay.setText(_translate("MainWindow", "Status:", None))
        self.lblCurrentStatus.setText(_translate("MainWindow", "Idle", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Upload", None))
        self.gBoxAdditionalTags.setTitle(_translate("MainWindow", "Additional Tags", None))
        self.cBoxSearchStudentLife.setText(_translate("MainWindow", "Student Life", None))
        self.cBoxSearchPeople.setText(_translate("MainWindow", "People", None))
        self.cBoxSearchAcademics.setText(_translate("MainWindow", "Academics", None))
        self.cBoxSearchClubs.setText(_translate("MainWindow", "Clubs", None))
        self.cBoxSearchSports.setText(_translate("MainWindow", "Sports", None))
        self.cBoxSearchCrowds.setText(_translate("MainWindow", "Crowds", None))
        self.gBoxClassTags.setTitle(_translate("MainWindow", "Class Tags", None))
        self.cBoxSearchSenior.setText(_translate("MainWindow", "Senior", None))
        self.cBoxSearchJunior.setText(_translate("MainWindow", "Junior", None))
        self.cBoxSearchSophomore.setText(_translate("MainWindow", "Sophomore", None))
        self.cBoxSearchFreshmen.setText(_translate("MainWindow", "Freshmen", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Date Filter", None))
        self.label.setText(_translate("MainWindow", "Starting Date:", None))
        self.label_2.setText(_translate("MainWindow", "Ending Date:", None))
        self.btnResetDateFilter.setText(_translate("MainWindow", "Reset Filter", None))
        self.gBoxOpponentTags.setTitle(_translate("MainWindow", "Opponent Tag", None))
        self.lEditSearchOpponent.setPlaceholderText(_translate("MainWindow", "Opponent (if applicable) (Hit \'Enter\')", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Photo Database Information", None))
        self.label_3.setText(_translate("MainWindow", "Total Photos", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Search Photo Database", None))
        self.lEditTagSearch.setPlaceholderText(_translate("MainWindow", "Type Tags (separated by spaces) to Search...", None))
        self.btnClearTagSearch.setText(_translate("MainWindow", "Clear", None))
        self.btnTagSearchRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.btnShowInFolder.setText(_translate("MainWindow", "Show in Folder", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Browse", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionAbout_Application.setText(_translate("MainWindow", "About Application", None))
